# Generated by Django 3.2 on 2022-09-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('entry_content', models.TextField()),
            ],
        ),
    ]
